[package]
name = "bff"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.7", features = ["macros"] }
tower-http = { version = "0.6.6", features = ["cors"] }
tokio = { version = "1.32.0", features = ["full"] }
serde = "1.0.188"
serde_json = "1"
futures = "0.3.28"
jsonwebtoken = "9"
dotenvy = "0.15"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
anyhow = "1"

[dependencies.mongodb]
version = "3.3.0"